<!doctype html>
<html <?= $htmlAttributes ?>>
    <head <?= $headAttributes ?>>
        <link
            rel="preload"
            href="<?= $this->getViewFileUrl('fonts/roboto-v30-latin-300.woff2') ?>"
            as="font"
            type="font/woff2"
            crossorigin
        >

        <link
            rel="preload"
            href="<?= $this->getViewFileUrl('fonts/roboto-v30-latin-regular.woff2') ?>"
            as="font"
            type="font/woff2"
            crossorigin
        >

        <link
            rel="preload"
            href="<?= $this->getViewFileUrl('fonts/roboto-v30-latin-500.woff2') ?>"
            as="font"
            type="font/woff2"
            crossorigin
        >

        <link
            rel="preload"
            href="<?= $this->getViewFileUrl('fonts/roboto-v30-latin-700.woff2') ?>"
            as="font"
            type="font/woff2"
            crossorigin
        >

        <style>
            @font-face {
                font-family: 'Roboto';
                font-weight: 300;
                font-style: normal;
                font-display: block;
                src: url('<?= $this->getViewFileUrl('fonts/roboto-v30-latin-300.eot') ?>'); /* IE9 Compat Modes */
                src: local(''),
                url('<?= $this->getViewFileUrl('fonts/roboto-v30-latin-300.eot') ?>?#iefix') format('embedded-opentype'), /* IE6-IE8 */
                url('<?= $this->getViewFileUrl('fonts/roboto-v30-latin-300.woff2') ?>') format('woff2'), /* Super Modern Browsers */
                url('<?= $this->getViewFileUrl('fonts/roboto-v30-latin-300.woff') ?>') format('woff'), /* Modern Browsers */
                url('<?= $this->getViewFileUrl('fonts/roboto-v30-latin-300.ttf') ?>') format('truetype'), /* Safari, Android, iOS */
                url('<?= $this->getViewFileUrl('fonts/roboto-v30-latin-300.svg') ?>#Roboto') format('svg'); /* Legacy iOS */
            }

            @font-face {
                font-family: 'Roboto';
                font-weight: 400;
                font-style: normal;
                font-display: block;
                src: url('<?= $this->getViewFileUrl('fonts/roboto-v30-latin-700.eot') ?>'); /* IE9 Compat Modes */
                src: local(''),
                url('<?= $this->getViewFileUrl('fonts/roboto-v30-latin-regular.eot') ?>?#iefix') format('embedded-opentype'), /* IE6-IE8 */
                url('<?= $this->getViewFileUrl('fonts/roboto-v30-latin-regular.woff2') ?>') format('woff2'), /* Super Modern Browsers */
                url('<?= $this->getViewFileUrl('fonts/roboto-v30-latin-regular.woff') ?>') format('woff'), /* Modern Browsers */
                url('<?= $this->getViewFileUrl('fonts/roboto-v30-latin-regular.ttf') ?>') format('truetype'), /* Safari, Android, iOS */
                url('<?= $this->getViewFileUrl('fonts/roboto-v30-latin-regular.svg') ?>#Roboto') format('svg'); /* Legacy iOS */
            }

            @font-face {
                font-family: 'Roboto';
                font-weight: 500;
                font-style: normal;
                font-display: block;
                src: url('<?= $this->getViewFileUrl('fonts/roboto-v30-latin-500.eot') ?>'); /* IE9 Compat Modes */
                src: local(''),
                url('<?= $this->getViewFileUrl('fonts/roboto-v30-latin-500.eot') ?>?#iefix') format('embedded-opentype'), /* IE6-IE8 */
                url('<?= $this->getViewFileUrl('fonts/roboto-v30-latin-500.woff2') ?>') format('woff2'), /* Super Modern Browsers */
                url('<?= $this->getViewFileUrl('fonts/roboto-v30-latin-500.woff') ?>') format('woff'), /* Modern Browsers */
                url('<?= $this->getViewFileUrl('fonts/roboto-v30-latin-500.ttf') ?>') format('truetype'), /* Safari, Android, iOS */
                url('<?= $this->getViewFileUrl('fonts/roboto-v30-latin-500.svg') ?>#Roboto') format('svg'); /* Legacy iOS */
            }

            @font-face {
                font-family: 'Roboto';
                font-weight: 700;
                font-style: normal;
                font-display: block;
                src: url('<?= $this->getViewFileUrl('fonts/roboto-v30-latin-700.eot') ?>'); /* IE9 Compat Modes */
                src: local(''),
                url('<?= $this->getViewFileUrl('fonts/roboto-v30-latin-700.eot') ?>?#iefix') format('embedded-opentype'), /* IE6-IE8 */
                url('<?= $this->getViewFileUrl('fonts/roboto-v30-latin-700.woff2') ?>') format('woff2'), /* Super Modern Browsers */
                url('<?= $this->getViewFileUrl('fonts/roboto-v30-latin-700.woff') ?>') format('woff'), /* Modern Browsers */
                url('<?= $this->getViewFileUrl('fonts/roboto-v30-latin-700.ttf') ?>') format('truetype'), /* Safari, Android, iOS */
                url('<?= $this->getViewFileUrl('fonts/roboto-v30-latin-700.svg') ?>#Roboto') format('svg'); /* Legacy iOS */
            }

        </style>

        <?php
            $isCheckout = strpos($bodyAttributes, 'page-layout-checkout');
            $criticalStyles;
            if ($isCheckout) {
                $criticalStyles = $this->assetRepo->createAsset('css/critical-checkout.css')->getContent();
                $inlineStyles = str_replace('../images', $this->getViewFileUrl('images'), $criticalStyles);
                $inlineStyles = str_replace('critical.css.map', $this->getViewFileUrl('css/critical-checkout.css.map'), $inlineStyles);
            } else {
                $criticalStyles = $this->assetRepo->createAsset('css/critical.css')->getContent();
                $inlineStyles = str_replace('../images', $this->getViewFileUrl('images'), $criticalStyles);
                $inlineStyles = str_replace('critical.css.map', $this->getViewFileUrl('css/critical.css.map'), $inlineStyles);
            }
        ?>

        <style>
            <?= $inlineStyles; ?>
        </style>

        <?php if ($isCheckout): ?>
            <link
                href="<?= $this->getViewFileUrl('Magento_Checkout/checkout.css') ?>"
                rel="stylesheet"
                as="style"
                media="print"
                onload="this.media='all'"
            />
        <?php else: ?>
            <link
                href="<?= $this->getViewFileUrl('css/styles.css') ?>"
                rel="stylesheet"
                as="style"
                media="print"
                onload="this.media='all'"
            />
        <?php endif; ?>

        <?= $requireJs ?>
        <?= $headContent ?>
        <?= $headAdditional ?>
    </head>
    <body
        data-container="body"
        data-mage-init='{
            "loaderAjax": {},
            "loader": {
                "icon": "<?= $loaderIcon ?>"
            }
        }'
        <?= $bodyAttributes ?>
    >
        <?= $layoutContent ?>
    </body>
</html>
