<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Store\Block\Switcher $block */
?>
<?php if (count($block->getGroups())>1) : ?>

    <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
    <div
            class="
            dropdown-list
            dropdown-list--detailed-content
            footer__dropdown-switcher
            margin-right-xs
        "
            data-ui-id="language-switcher"
            data-mage-init='{ "dropdownList": {} }'
            id="switcher-language<?= $block->escapeHtmlAttr($id) ?>"
    >
        <div
                class="
                actions
                dropdown
                options
                switcher-options
            "
        >
            <ul class="dropdown-list__list">
                <li
                        class="
                        dropdown-list__item
                        dropdown-list__item--collapse
                    "
                >
                    <button
                            class="dropdown-list__label"
                            aria-expanded="false"
                            aria-controls="dropdown-language-content"
                    >
                        <?= $block->escapeHtml($block->getStoreName()) ?>
                        <svg
                                class="
                                icon
                                dropdown-list__icon
                            "
                                role="presentation"
                                focusable="false"
                        >
                            <use href="<?= $block->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg#angle-down')) ?>"></use>
                        </svg>
                    </button>
                    <div
                            id="dropdown-language-content"
                            class="dropdown-list__content"
                            aria-hidden="true"
                    >
                        <ul
                                class="list"
                                data-target="dropdown"
                        >
                            <?php foreach ($block->getGroups() as $_group) : ?>
                                <?php if ($_group->getId() != $block->getCurrentStoreId()) : ?>
                                    <li
                                            class="
                                            list__item
                                            view-<?= $block->escapeHtml($_group->getCode()) ?>
                                            switcher-option
                                        "
                                    >
                                        <a
                                                href="#" data-post='<?= /* @noEscape */ $block->getTargetStorePostData($_group->getDefaultStore()) ?>'
                                                class="link"
                                                title="<?= $block->escapeHtmlAttr($_group->getName()) ?>"
                                        >
                                            <?= $block->escapeHtml($_group->getName()) ?>
                                        </a>
                                    </li>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </li>
            </ul>

        </div>
    </div>


<?php endif; ?>
