<?php
    $scrollTop = $this->getChildHtml('footer-scroll-top');
    $topBar = $this->getChildHtml('footer-top-bar');
    $footerMenu = $this->getChildHtml('footer-menu');
    $bottomBar = $this->getChildHtml('footer-bottom-bar');
    $cookieMessage = $this->getChildHtml('footer-cookie-message');
?>

<?php if ($scrollTop || $topBar || $footerMenu): ?>
    <div class="footer__handler container">
        <?php if ($scrollTop): ?>
            <?= /* @noEscape */ $scrollTop ?>
        <?php endif; ?>

        <?php if ($topBar): ?>
            <section class="footer__top-bar">
                    <?= /* @noEscape */ $topBar ?>
            </section>
        <?php endif; ?>

        <?php if ($footerMenu): ?>
            <section class="footer__links">
                <?= /* @noEscape */ $footerMenu ?>
            </section>
        <?php endif; ?>
    </div>
<?php endif; ?>

<?php if ($bottomBar): ?>
    <section class="footer__bottom-bar">
        <div class="footer__bottom-bar-handler container">
            <?= /* @noEscape */ $bottomBar ?>
            <?= $block->getChildHtml('switchers.wrapper') ?>
        </div>
    </section>
<?php endif; ?>

<?php if ($cookieMessage): ?>
    <div
        class="cookie-message"
        data-type="cookie"
        tabindex="0"
        aria-label="<?= $block->escapeHtmlAttr(__('Cookie policy message')) ?>"
        data-mage-init='{ "cookieMessage": { } }'
    >

        <div class="cookie-message__container">
            <?= /* @noEscape */ $cookieMessage ?>

            <button
                class="
                    button
                    button--icon
                    cookie-message__button
                    cookie-message__close
                    button--rotate-icon
                "
                type="button"
                aria-label="<?= $block->escapeHtmlAttr(__('Close cookie message')) ?>"
            >
                <svg
                    class="
                        icon
                        button__icon
                        cookie-message__button-icon
                    "
                    role="presentation"
                    focusable="false"
                >
                    <use href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#close')) ?>"></use>
                </svg>
            </button>
        </div>
    </div>
<?php endif; ?>
