<?php
/** @var \Phpro\CookieConsent\ViewModel\Cookie $viewModel */
$viewModel = $block->getViewModel();
?>
<div class="phpro-cookie-notice" style="display: none;">
    <div class="notice-wrapper">
        <div class="notice__description">
            <span>
                <?= __('We use functional and analytical cookies to make our website better.') ?>
                <?= __('Would you like to know more about our cookies? Click on "Cookie settings".') ?>
            </span>
        </div>
        <div class="notice__actions">
            <button class="button action primary notice__btn notice__btn-accept">
                <?= __('Accept cookies') ?>
            </button>
            <button class="button button--secondary action primary notice__btn notice__btn-settings">
                <?= __('Cookie settings') ?>
            </button>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Phpro_CookieConsent/js/notice": {
            "cookie_name": "<?= $viewModel->getCookieName(); ?>",
            "expiration": <?= $viewModel->getExpirationDays(); ?>,
            "secure": <?= $viewModel->isFrontUrlSecure(); ?>,
            "cookie_groups_data": <?= $viewModel->getGroupsData(); ?>
        }
    }
}
</script>
